info:
  contact: {}
paths:
  /products:
    get:
      description: Devuelve productos con filtros y orden
      parameters:
      - description: Texto a buscar
        in: query
        name: q
        type: string
      - description: Precio mínimo
        in: query
        name: minPrice
        type: number
      - description: Precio máximo
        in: query
        name: maxPrice
        type: number
      - description: Campo para ordenar
        enum:
        - price
        - rating
        in: query
        name: sort
        type: string
      - description: Orden
        enum:
        - asc
        - desc
        in: query
        name: order
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Lista de productos
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Error interno
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Lista productos
      tags:
      - products
  /products/{id}:
    get:
      description: Devuelve el detalle de un producto por ID
      parameters:
      - description: ID del producto
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Producto encontrado
          schema:
            additionalProperties: true
            type: object
        "404":
          description: Producto no encontrado
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Detalle de producto
      tags:
      - products
swagger: "2.0"
